FROM discrete-labs

RUN apt-get update && apt-get install -y \
    texlive-base \
    texlive-latex-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-lang-cyrillic \
    texlive-fonts-recommended \
    && rm -rf /var/lib/apt/lists/*
